import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pop = Poppins({
  weight:["300","400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     < >
    <ClerkProvider>
    <html lang="en" className="dark">
      <body
        className={`${pop.className}antialiased`}>
           
          <div className="w-full h-screen">
              {children}
            </div>
            
      </body>
    </html>
    </ClerkProvider>
    </>
  );
}
